### ISSUE TITLE
App does file shares without permissions and cause spam to users

### ISSUE THREAD

**Issue by burner-** [CADViewer/NextCloud#15]
This app will create folder and share it with other users. Target users will get "shared »CADViewer - Markup« with you " And most of those account did not have even active accounts. So poorly designed software shoud not be even nexcloud appstore.

**Comment by CADViewer** [comment]
@burner- yes, the requirement has been redone, so the Markup Folder for PDF is being created for the user running CADViewer only (no global share).  The user can then in a second stage select who to share with.  It will be included in the next release.

**Comment by burner-** [comment]
Just wondering how many other equally bad solution this software have. Sorry to say but that shows quite exreme bad judgement at development. Whole code base should be reviewed someone who have ever slight understanding of security design.

**Comment by CADViewer** [comment]
@burner- Tapio, many thanks for your review of this matter. CADViewer v8.33.1 is now uploaded.  Only when a user decides to make a PDF of their drawing/section of a drawing + annotations, is the CADViewer-Markup folder created, and for this user only, and in which explicit action is needed from the user to create the PDF (and thus create the local folder).   No global folders are created.
