### ISSUE TITLE
Can not create some type file

### ISSUE THREAD

**Issue by IamTaoChen** [CADViewer/NextCloud#18]
While I enable CASViewer, i can not create some type file, such like, *.md and office.

My nextcloud version is 25.0.4
And CADViewer is 8.38.1.

**Comment by CADViewer** [comment]
@TaoChan1005 , hello, please describe your issue in more detail?  In our reference implementation, we can load office files up (such as .docx) and use the separate viewer allocated to that file-format and run CADViewer afterwards.   CADViewer should only work with AutoCAD and MicroStation files by their default file format, or for bitmaps and svg/svgz using the ... menu.

**Comment by IamTaoChen** [comment]
Yes, I can open a .doc file which exists. But I can not create a .doc file. i use onlyoffice

**Comment by CADViewer** [comment]
@TaoChan1005 , try and open the DevTools (Ctrl+Shift+I) on your browser,  then capture the Console, trace for Errors and Info.   Share this information.

**Comment by IamTaoChen** [comment]
[AAAA.com-1677591446540.log](https://github.com/CADViewer/NextCloud/files/10850849/AAAA.com-1677591446540.log)

**Comment by CADViewer** [comment]
@TaoChan1005 , we have now made a new release, v8.40.2, where the EventListeners inside our application that OpenOffice fires off when they load files are removed, please check and let us know.

**Comment by IamTaoChen** [comment]
Great. This has been solved.

**Comment by CADViewer** [comment]
Great👍
