### ISSUE TITLE
Can not open any dwg files

### ISSUE THREAD

**Issue by bluestar800** [CADViewer/NextCloud#19]
nextcloud 25.0.3（In host ，not docker）
CADViewer v8.38.1 in ./nextcloud/apps

My nextcloud config.php has these settings
` 'apps_paths' =>
  array (
    0 =>
    array (
      'path' => '/var/www/nextcloud/apps',
      'url' => '/apps',
      'writable' => false,
    ),
    1 =>
    array (
      'path' => '/var/www/nextcloud/custom_apps',
      'url' => '/custom_apps',
      'writable' => true,
    ),
  ),
`

For install cadviewer ， I git clone it in ./nextcloud/apps. And follow the step in [README.md] to set up.

There are no  errors in the results of Cadviewer Doctor check . By the way there is no any logs to show me anythings
![image](https://user-images.githubusercontent.com/30996974/222041981-58f108df-83b4-4ec9-82fa-f62df84c3211.png)

But I cannot open any dwg files, it told me like this
![image](https://user-images.githubusercontent.com/30996974/222041804-eb37e932-a91b-4c2e-ab9c-df950578d6ef.png)

nextcloud logs  have many errors of cadviewer , But  they are the same one.
`OCP\AppFramework\QueryException: Could not resolve OCA\Cadviewer\AppInfo\ViewerListener! Class OCA\Cadviewer\AppInfo\ViewerListener does not exist

/var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php - line 133:
OC\AppFramework\Utility\SimpleContainer->resolve()

/var/www/nextcloud/lib/private/ServerContainer.php - line 161:
OC\AppFramework\Utility\SimpleContainer->query()

/var/www/nextcloud/lib/private/EventDispatcher/ServiceEventListener.php - line 71:
OC\ServerContainer->query()

/var/www/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php - line 251:
OC\EventDispatcher\ServiceEventListener->__invoke()

/var/www/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php - line 73:
Symfony\Component\EventDispatcher\EventDispatcher->callListeners()

/var/www/nextcloud/lib/private/EventDispatcher/EventDispatcher.php - line 88:
Symfony\Component\EventDispatcher\EventDispatcher->dispatch()

/var/www/nextcloud/lib/private/EventDispatcher/EventDispatcher.php - line 100:
OC\EventDispatcher\EventDispatcher->dispatch()

/var/www/nextcloud/apps/files/lib/Controller/ViewController.php - line 304:
OC\EventDispatcher\EventDispatcher->dispatchTyped()

/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 225:
OCA\Files\Controller\ViewController->index()

/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 133:
OC\AppFramework\Http\Dispatcher->executeController()

/var/www/nextcloud/lib/private/AppFramework/App.php - line 172:
OC\AppFramework\Http\Dispatcher->dispatch()

/var/www/nextcloud/lib/private/Route/Router.php - line 298:
OC\AppFramework\App::main()

/var/www/nextcloud/lib/base.php - line 1047:
OC\Route\Router->match()

/var/www/nextcloud/index.php - line 36:
OC::handleRequest()`

Feel free to let me know what more info you need. Thanks for help again

**Comment by bluestar800** [comment]
OK, I think I solved that problem.
thanks kroko for reminding me at https://github.com/CADViewer/NextCloud/issues/3#issuecomment-1428660465

I add the code about /apps/cadviewer/converter/php/ placed before location ~ \.php(?:$|/) in my nginx config
`location /apps/cadviewer/converter/php/ {
        location ~ \.php$ {
            fastcgi_split_path_info ^(.+?\.php)(/.*)$;
            set $path_info $fastcgi_path_info;
            try_files $fastcgi_script_name =404;
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_param PATH_INFO $path_info;
            fastcgi_param HTTPS on;
            fastcgi_param modHeadersAvailable true; 
            fastcgi_param front_controller_active true; 
            fastcgi_pass unix:/run/php/php7.4-fpm_retractedinfo-nginx-socket_clouduser_nginx_socket.sock;
            fastcgi_intercept_errors on;
            fastcgi_request_buffering off;
            fastcgi_max_temp_file_size 0;
        }
        try_files $uri $uri/ =403;
    }`

Note！！！This code must be changed to match your PHP Settings
` fastcgi_pass unix:/run/php/php7.4-fpm_retractedinfo-nginx-socket_clouduser_nginx_socket.sock;`

**Comment by CADViewer** [comment]
@bluestar800 , great that you solved it!  We will move this into the general documentation sheet.

**Comment by nightdread** [comment]
![image](https://github.com/CADViewer/NextCloud/assets/71598118/9c673fda-cf9b-40d6-a5dc-c98b985d25a4)
 I also added such a configuration, but still have error 126
