### ISSUE TITLE
how to change font

### ISSUE THREAD

**Issue by bluestar800** [CADViewer/NextCloud#21]
how to change font？
There's  a lot of text on the open drawing that turns into ?
I uploaded a .shx font that used in autocad software to the font folder，how can I use it in cadviewer?

**Comment by CADViewer** [comment]
@bluestar800 , can you please send us a sample file to test with. Please send to e-mail: developer@tailormade.com , also please send the .shx font.  I am assuming there is a shx/unicode translation that is not properly taking place with chinese (?) fonts., but we need to test

**Comment by bluestar800** [comment]
Thanks for your help. 
 I would like to know how to make this .shx font take effect, whether it will take effect automatically if it is placed in the font folder, or do I need to modify some files?  If need to modify the file, can you tell me which one and how to modify it ?  I visited your website for help knowlege, but I still don't know how and where to add the -df parameter to set the default font.  Font mapping doesn't suit my current needs.

Yes ，your right，the drawing have chinese . I will sent your mailbox later

**Comment by CADViewer** [comment]
@bluestar800 , I think there may be an issue with with the .shx rendering, we will investigate.  I loaded a reference Chinese drawing, then I opened the settings modal, I removed the parameter strokea , and then I clicked reload + OK (arrow button),  with this operation, I get the font up as TTF. Can you check if this works for you?  (we will obviously check when we get your .shx/.dwg)


![image](https://user-images.githubusercontent.com/61973235/222152627-09bcafc0-2a84-4390-83a4-1f6216ead881.png)

**Comment by bluestar800** [comment]
@CADViewer 
I did the same, still no change.

I sent you the email a few minutes ago  ：）

![image](https://user-images.githubusercontent.com/30996974/222188059-11d1b776-a548-4539-97e1-ac04b6bc27f8.png)

**Comment by CADViewer** [comment]
@bluestar800 ,hello we now have posted version v8.46.8, where we leave TTF correctly translated, your drawing looks good with that.  Furtermore, we will expose to the interface the list with unmapped fonts, so the mapping files can be done (correctly) accordingly.


![image](https://user-images.githubusercontent.com/61973235/224799476-99eec386-98e3-4568-9779-65ec060404e1.png)
