### ISSUE TITLE
File Permission Problem

### ISSUE THREAD

**Issue by ashcoft** [CADViewer/NextCloud#24]
file has been 0777
![image](https://user-images.githubusercontent.com/1115854/224573737-02ceae0c-9d8f-4577-b9d6-84fd5e6e9a78.png)

but after scanning the file still not 0777
![image](https://user-images.githubusercontent.com/1115854/224573784-6fc82c83-42f8-4ba9-a06a-4b28670e4c46.png)

thanks in advance

**Comment by CADViewer** [comment]
@ashcoft , hello,  can you please update and test again. Currently we have 8.46.8 up, where the mapping is to ax2023_L64_12_23_109b.   The important point is that the file in the folder have full permission, however, the CADViewer Doctor should reflect this.

**Comment by ashcoft** [comment]
Yes, now the permissions is resolved.

Thanks in advance
