### ISSUE TITLE
Stops working after upgrade Nextcloud 25.0.4 -> 25.0.5

### ISSUE THREAD

**Issue by s-rosenfeld** [CADViewer/NextCloud#31]
![Screenshot_20230325_083056](https://user-images.githubusercontent.com/12949115/227696144-19e77b56-f7ca-4a09-9ec0-d6df494d4603.png)

The reason is in /var/www/nextcloud/.htaccess, the following line has disappeared there:

RewriteCond %{REQUEST_FILENAME} !/apps/cadviewer/converter/php/*\.*

After inserting this line manually, everything works, except for the icons on the files in the Nextcloud interface.

**Comment by CADViewer** [comment]
@s-rosenfeld , hello , yes we have seen this when upgrading NextCloud 24 versions. The issue with RewriteCond is that we can't owerwrite this  file  (and perhaps shouldn't).  We are requestion the NextCloud internal developers assistance on this issue.  (yes, NextCloud compiles the icons into a system file, which takes strange ways. We had the file-icons appear and disappear with upgrades with no opbvious pattern.  Again, this we push into NextCloud proper.
