### ISSUE TITLE
Cannot open files. 

### ISSUE THREAD

**Issue by bytec77** [CADViewer/NextCloud#32]
Hi folks, 

installed the newest version set right permissions and cad viewer  doctor says everything fine but I cannot open files. 

Here the console output.

`Uncaught (in promise) Error: Your focus-trap must have at least one container with at least one tabbable node in it at all times
    at h (focus-trap.esm.js:358:23)
    at Object.activate (focus-trap.esm.js:635:7)
    at NcModal.js:2:170598
    at d (NcModal.js:2:159742)
    at Generator.<anonymous> (NcModal.js:2:161079)
    at Generator.next (NcModal.js:2:160105)
    at A (NcModal.js:2:165730)
    at r (NcModal.js:2:170752)
h @ focus-trap.esm.js:358
activate @ focus-trap.esm.js:635
(anonym) @ NcModal.js:2
d @ NcModal.js:2
(anonym) @ NcModal.js:2
(anonym) @ NcModal.js:2
A @ NcModal.js:2
r @ NcModal.js:2
Promise.then (async)
A @ NcModal.js:2
r @ NcModal.js:2
(anonym) @ NcModal.js:2
(anonym) @ NcModal.js:2
useFocusTrap @ NcModal.js:2
mounted @ NcModal.js:2
Fe @ vue.runtime.esm.js:3019
dn @ vue.runtime.esm.js:4042
insert @ vue.runtime.esm.js:4166
C @ vue.runtime.esm.js:6953
Xo.nodeOps @ vue.runtime.esm.js:8215
t._update @ vue.runtime.esm.js:3777
i @ vue.runtime.esm.js:3880
t.get @ vue.runtime.esm.js:3450
t.run @ vue.runtime.esm.js:3532
yn @ vue.runtime.esm.js:4168
(anonym) @ vue.runtime.esm.js:3158
He @ vue.runtime.esm.js:3089
Promise.then (async)
Ne @ vue.runtime.esm.js:3102
Ge @ vue.runtime.esm.js:3280
wn @ vue.runtime.esm.js:4254
t.update @ vue.runtime.esm.js:3523
t.notify @ vue.runtime.esm.js:734
set @ vue.runtime.esm.js:979
Gn.set @ vue.runtime.esm.js:5381
viewCadFileActionHandler @ CADViewerCanvas.vue:922
action @ merged-index.js?v=b527208a-11:3067
_onClickFile @ merged-index.js?v=b527208a-11:5042
bt @ _executeBound.js:8
(anonym) @ bind.js:10
(anonym) @ restArguments.js:16
dispatch @ jquery.js:5430
m.handle @ jquery.js:5234
`

**Comment by CADViewer** [comment]
@bytec77 , hello , can you please send the console info pane output. This will list the communication between the CADViewer front-end and the back-end, and it tells us if you load in icons correctly, .  Also, just below the cadviewer doctor, there is a button to download or display the conversion log, please send that as well. thanks!

**Comment by Floppik** [comment]
Same issue. Log from console here: https://pastebin.com/eTsHvT15

![image](https://user-images.githubusercontent.com/38560023/229713687-4b599c59-7dfd-4de6-9daf-fb0057d2b208.png)

![image](https://user-images.githubusercontent.com/38560023/229713771-bc923444-0387-41e1-a181-caf980dd096a.png)

![image](https://user-images.githubusercontent.com/38560023/229713943-62e611dc-4fad-45e9-a820-97b3fcbb54d0.png)

**Comment by CADViewer** [comment]
@bytec77, @Floppik  Please install latest version of CADViewer v8.88.5 and let us know the result of your testing.  Thanks!

**Comment by Floppik** [comment]
Same error: 
![image](https://github.com/CADViewer/NextCloud/assets/38560023/98847b9f-1ecf-4119-8076-6542edba93fe)
[call-Api_Conversion_log.txt](https://github.com/CADViewer/NextCloud/files/12646343/call-Api_Conversion_log.txt)

**Comment by CADViewer** [comment]
Hello @Floppik  , with the latest version 9.47.1, we have added code to check the .httacess and update the rewrite conditions, and if there is insufficient permissions, we now provide an error message in the admin console with instructions.
