### ISSUE TITLE
License Key Expired

### ISSUE THREAD

**Issue by kevinkuan1969** [CADViewer/NextCloud#33]
Newly discovered Nextcloud has integrated with CADViewer and find great potential to target the engineering firms........
For my past 2 years knowledge with Nextcloud, most of the applications are free unless want to explore more features......

Few questions:

1. Is CADViewer still free to use in nextcloud?
2. If not, any temporary to use for testing, 30 days? or as and when any demo to client?
3. Just installed the latest Nextcloud 26 or Hub 4 and CADViewer, found the error when apply the license key from your server
![image](https://user-images.githubusercontent.com/80019930/231120294-f4d6d8e2-5db8-4332-8880-f7b23f674594.png)
as well the error as below
![image](https://user-images.githubusercontent.com/80019930/231120461-1246da4b-4b8e-42fc-bba8-0a8aa32822ca.png)

**Comment by CADViewer** [comment]
@kevinkuan1969 ,   
1) You can use CADViewer with all functionality enabled, you'll just see a "trial" watermark, which will disappear with a full license. 
2) Currently, the trial mark is permanent in unlicensed mode, so there is no time-out.  
2b) Yes, if you are demonstrating to a customer, then surely we can arrange for you to get a temporary usage license key, so you get a clean canvas during demonstrations. 
3) The error is something else, I think you have not run the back-end script to give the server full chmod 777 permissions, or you may have to change the .htaccess file, to ensure the php scripts are properly re-routed, please see: https://github.com/CADViewer/NextCloud/blob/main/README.md .
4) If you like, please write us directly, developer@tailormade.com , and we can continue the discussion on 2b) above. Thanks!

**Comment by kevinkuan1969** [comment]
Thanks for the great help!
Before we go out to the field, we need to familiar the solution offerings as well as it is ready for testing purpose.
We have gone thru all the steps and still get it works and hope you can help.

Here the settings .htaccess and debug report:
![image](https://user-images.githubusercontent.com/80019930/231398408-f1012c7e-60f2-41ea-a407-4fba4f4d79e3.png)

![image](https://user-images.githubusercontent.com/80019930/231398028-5ba5a329-0e3f-4f51-a588-2d43de363bcf.png)

Downloaded some sample files and the Nextcloud can recognize it as AutoCAD file but it did not appear CADViewer to open
![image](https://user-images.githubusercontent.com/80019930/231398920-9800fe18-96c6-4bf9-b24f-e15a8f19d2b9.png)

Attached the sample CAD file used for our testing and kindly refer it
https://demo.analytic360.biz/index.php/s/GsmkDCCXD9nbiMD

**Comment by CADViewer** [comment]
@kevinkuan1969 , I think your settings are correct, as I also get an error when I try to load bridge.dxf,  the same error as you,  I am passing it over for a developer to take a look, as this is a conversion error on the server.   Can you please test the attached Plane.dwg file and let me know the result. 
[Plane.zip](https://github.com/CADViewer/NextCloud/files/11210944/Plane.zip)
, you should get a display like this:
![image](https://user-images.githubusercontent.com/61973235/231446728-4e0a0b48-0d3d-4418-941a-6c340cadc0f6.png)

**Comment by CADViewer** [comment]
@kevinkuan1969 , I now got developer feedback regarding your DXF file:  It is a partial DXF file that just contains the entities section and not the header, block definitions (no blocks in the file, but still MODELSPACE and PAPERSPACE would be defined if not used), layers (only Layer 0 is used), fonts (no text in the file, but still..)  . It is not supported by the importer, but we can write a component that pads the drawing so its become a properly formatted DXF.

**Comment by kevinkuan1969** [comment]
No worry for the former DXF file and it was downloaded from other website for testing purpose.
I tried to open Plane.dwg and cannot see anything. 

![image](https://user-images.githubusercontent.com/80019930/231493733-783ea609-46af-40a3-8bb3-b1aa7e11fd69.png)



By right if the setting is correct, the CADViewer should be displayed as one of the item:
![image](https://user-images.githubusercontent.com/80019930/231493440-3ff6c193-aa21-45b0-96b5-502f6a6d7bf8.png)

**Comment by CADViewer** [comment]
Please do two things:   
1) Send the content of the browser developer console,   Ctrl+Shift+I (inspector), both information traces and errors.    
2) In the Admin panel in NextCloud CADViewer, download the Api Conversion log and send this to us.

**Comment by kevinkuan1969** [comment]
Please find below and hope it helps:
![image](https://user-images.githubusercontent.com/80019930/231505439-dba518ec-b869-47c0-8509-afae53e62e35.png)
![image](https://user-images.githubusercontent.com/80019930/231505631-814ccaa9-39bc-4e5a-a5b3-779176597fc7.png)

API Conversion Log - https://demo.analytic360.biz/index.php/s/3EEXY6wK2eDeMdN

**Comment by CADViewer** [comment]
If I look at the conversion.log, it contains the proper link to the converted drawing: https://demo.analytic360.biz/apps/cadviewer/converter//php//getFile_09.php?remainOnServer=1&fileTag=f556295049&Type=svgz  .  The Inspector did not give the trace from the info messages.  Will you be able to set up a sample user so, we can test on your instance?   You can react me at either developer@tailormade.com or on casper.harnung@tailormade.com .  Thanks!

**Comment by kevinkuan1969** [comment]
Please find below:
     https://demo.analytic360.biz

1.  login id - 'developer'     password - 'developertailormade123'
2. login id - 'Casper'          password - 'casperharnung123'

Thanks.

**Comment by CADViewer** [comment]
Hi @kevinkuan1969 , thanks for the access. The error seems to be in the loading stage, when the drawing is already converted, we have not seen this before, so will have to add some debugging information  and have you download and install, so we can test more.  Will keep you posted!

**Comment by kevinkuan1969** [comment]
As far as Nextcloud is concerned, we have just downloaded the following app as below:
![image](https://user-images.githubusercontent.com/80019930/231803378-4c8354ac-12e9-4b8d-8e37-b067a8884443.png)

and the administration setting as below:
![image](https://user-images.githubusercontent.com/80019930/231803960-524d0196-002b-4c7d-bfaf-6ceed722d41a.png)
 
Kindly advise any additional apps or modules from Nextcloud need to be downloaded for the testing purpose. Thanks.

**Comment by kevinkuan1969** [comment]
Managed to open dwg files after upgrade to Nextcloud 26.0.1. Thanks.
