### ISSUE TITLE
Problem with mouse hover.

### ISSUE THREAD

**Issue by foxhoundv** [CADViewer/NextCloud#4]
There is a visual issue when mouse hovering over a file or folder. Just to the right of the Share icon there is a little underscore...
![image](https://user-images.githubusercontent.com/16512250/216151383-cc25f68b-068c-4706-805b-85b1efa7af94.png)

If I hover over a shared file or folder, there is an underscore before the three dots for actions...
![image](https://user-images.githubusercontent.com/16512250/216151443-ab55f723-4c3f-4ca7-86ba-eda7744f7a7e.png)

It doesn't hinder anything, just looks weird. If I disable CADViewer app it goes away.

**Comment by foxhoundv** [comment]
There is also an issue with font display when the app is enabled and when hovering over the profile icon at the top right.

This is with it disabled...
![image](https://user-images.githubusercontent.com/16512250/216153552-4e349e1d-a01d-49db-918f-fc1236e92d63.png)

With the app enabled...
![image](https://user-images.githubusercontent.com/16512250/216153436-6e353e51-8847-40eb-9527-761ed521dc78.png)

**Comment by CADViewer** [comment]
Issue one above with the _   css issue has been closed in version 8.22.2.

**Comment by CADViewer** [comment]
@foxhoundv , FYI: the css  _ (underscore) issue is fixed.
