### ISSUE TITLE
Stop telling people to perform chmod 777

### ISSUE THREAD

**Issue by Luticus** [CADViewer/NextCloud#40]
Your documentation suggests that people recursively chmod 777 several directories under the app's location in Nextcloud's app folder. This is a *VERY* bad practice. Generally speaking, save for symlinks, NO file on your system should ever have the 777 permission. This is made *much* worse by the fact that these files are under a directory served by Apache! The chmod 777 command is pretty much always completely overkill and unnecessary. 

I have tested the app so far and you can get it to function by doing a chmod +x to */apps/cadviewer/converter/converters/ax2024/linux/ax2023_L64_xx_yy_zz". I did NOT perform a 777 here. 

Then I followed the steps in troubleshooting and that seemed to fix the problem. 

However, my drawings now all have a banner with "for demonstration purposes" and the website url plastered all over the background, which is ugly, to say the least. You should probably make it clear in the Nextcloud store that the software will require a license that is prohibitively expensive.

**Comment by CADViewer** [comment]
@Luticus , thanks for your input!  We will set up a test case for mimimum permission settings and update the documentation accordingly.
