### ISSUE TITLE
I see watermark on cadviewer how to get rid off it?

### ISSUE THREAD

**Issue by musmans** [CADViewer/NextCloud#44]
![image](https://user-images.githubusercontent.com/24773338/237040071-c4a8a87b-8cf1-4956-bd0e-101de8f0f286.png)
It is a nextcloud viewer and shows watermark.

**Comment by CADViewer** [comment]
Hello @musmans , so basically the watermarks are there for users to be able work with the software, where companies can license, and add the license keys in the admin interface, which will remove the watermarks  and thus use it professionally.   We are planning to make special arrangements for single users in a next step.    Hope this helps!  If you want to know more about licensing you can contact us at support@tailormade.com or developer@tailormade.com

**Comment by musmans** [comment]
What is the cost for 20 users license please?

**Comment by CADViewer** [comment]
Hello @musmans , the best solution is CADViewer corporate (https://cadviewer.com/pricing/) , perpetual/one-off license, which start at $999 for 10 users,  and annual support of $249.75 , so $1248.75 first year.  Each additional user is $9.90 , so in your case for 20 users, it's then $1098 (perpetual/one-off) and $274.50 annual support, or $1372.50 first year.  Would be happy to give you the 10 extra users for free.   You can then add users as you move on.

**Comment by musmans** [comment]
I understand that, due to your circumstances in a developing country, the current licensing cost may be prohibitive. If it would be possible to reduce the total cost, including all associated fees, to $500 USD, I would be grateful and more than happy to proceed with the payment. Thank you for your consideration.




 We're poor country poor people with limited resources.

**Comment by CADViewer** [comment]
Hi @musmans , sure, please contact me at casper.harnung@tailormade.com and we continue over at regular email. Thanks!

**Comment by CADViewer** [comment]
discussion continued offline
