### ISSUE TITLE
Server Side Conversion Error, See Web Browser Developer Console for full trace

### ISSUE THREAD

**Issue by xiazhichen24** [CADViewer/NextCloud#48]
The below is the error printed in the console. I am using Nextcloud 26 within a docker container and using nginx as the reverse proxy.  CADViewer worked perfectly before I added nginx and SSL certificates.

The CADViewer Nextcloud is 8.67.18. And `permission.sh` and `.htaccess` are applied according to README.

![image](https://github.com/CADViewer/NextCloud/assets/111276342/a509bf0a-26a3-442d-970b-20ec9d805637)

**Comment by CADViewer** [comment]
Hi @xiazhichen24 , it seems to be a permission issue, possibly there is a different owner when applying the proxy?  try inside /cadviewer/converter/php/ to give call-Api_Conversion.php  full chmod 777 permission and check if call-Api_Conversion.txt has write permissions for the owner  (if you are comfortable, you can give chmod 777 on that also.).  If this moves further in the process, you must also then give  /converter/converters/files,  full write permission for all owners, and also give /converter/converters/ax2024/linux/ax2023_L64_xx_yy_zz  full permissions.  Let me know if it helps

**Comment by xiazhichen24** [comment]
Works perfectly! Thanks! 777 really comes to the rescue.

**Comment by CADViewer** [comment]
@xiazhichen24 , great, let me know if/when we can assist you further, and if you possibly want to move into a licensed version!
