### ISSUE TITLE
missing serverside modules

### ISSUE THREAD

**Issue by ferdiga** [CADViewer/NextCloud#52]
After installing the CAD Viewer Module an error "Server side conversion error, ....." is displayed.

After consulting 
https://cadviewer.com/cadviewertechdocs/backend/
I suggested to the service provider (Hetzner) to install the missing modules, which was declined.

Hence I suggest
* include the required modules in the distribution (if possible)
or
* check for the necessary modules and deny installation if missing, to avoid error messages.

**Comment by CADViewer** [comment]
Hello @ferdiga , so the back-end modules are definitely part of the installation, you can see the structure at: https://github.com/CADViewer/NextCloud/tree/main/converter/converters , what we typically see with a server conversion error as issues are permission related, or if the redirection of .htaccess does not map the php scripts for the CADViewer app folder, see: https://github.com/CADViewer/NextCloud/blob/main/README.md, and check if you can do the appropriate settings   .  Are you able to browse the /nextcloud/apps/cadviewer/ folder structure on your server?

**Comment by ferdiga** [comment]
thanks für looking into this,
and no, I can not access the server structure of the Hetzner NC and I am not able to modify any of the files mentioned above.
what I might try is to use the Federation Service and open the files on my private NC installation where I can access the server files. My last experience a while ago with Federation resulted in performance issues.

**Comment by ferdiga** [comment]
I updated to NC 26.0.2 and reinstalled the CADviewer module.
- No more error message.
- can load a DWG file without error
- nothing is displayed on a Macbook, sometimes no icons visible

any hint available?

**Comment by CADViewer** [comment]
Great, @ferdiga , that it works for you.   All icons and scripts are loaded into the DOM, that includes the drawing file itself, it's an SVG in the browser DOM, so it should work the same on a Macbook that on any other system, it should be browser dependent only.   I will close this item now, but I will have it tested on a Macbook against a test server.     Are you using Chrome on Macbook or  Safari?
