### ISSUE TITLE
CADViewer interfering with Nextcloud Office (richdocuments) / Share dialog.

### ISSUE THREAD

**Issue by Karamelmar** [CADViewer/NextCloud#68]
Originally this issue/thread on richdocuments was opened:
[https://github.com/nextcloud/richdocuments/issues/3199](https://github.com/nextcloud/richdocuments/issues/3199)

In short:
CADViewer causes Nextcloud Office to misaligne from the top, and when the share dialog is opened in NC Office, the share dialog opens behind Nextcloud Office. Please visite the original issue regarding screenshots.
This behavior also depends on which desktop resolution is used.
After disabling CADViewer NC Office works as expected again.

**Comment by ferdiga** [comment]
see also 
https://github.com/nextcloud/richdocuments/issues/3246

**Comment by CADViewer** [comment]
Hi @Karamelmar , thanks for the report, the issue is passed over to our development team.  Will notify you!

**Comment by CADViewer** [comment]
Scope of styling in CADViewer package updated.
