### ISSUE TITLE
Can't open file in NC 27.

### ISSUE THREAD

**Issue by nightdread** [CADViewer/NextCloud#69]
I installed the program following the instructions from GitHub, but when I open the file, a "loading" window appears and then just a blank screen.

Two errors appear in the Nextcloud log
![image](https://github.com/CADViewer/NextCloud/assets/71598118/4d6dbc89-c28d-44cc-92b7-de5c0e00c604)

I am using Nginx as a web server and php version 8.2.

Please help me to solve the problem with opening files.

![image](https://github.com/CADViewer/NextCloud/assets/71598118/bfbfe261-f901-408d-9083-021b5567a86f)

**Comment by CADViewer** [comment]
Hello @nightdread , the E126 is typically when the back-end CAD converter AX2023 does not have the appropriate permissions. Can you please share the trace from the  "API Conversion Log" in the Admin Interface? https://cadviewer.com/cadviewerusermanual/referenceapplications/nextcloud/admin/#api-conversion-log, and please also follow the instructions for: https://github.com/CADViewer/NextCloud/blob/main/README.md  , permission part.  thanks!

**Comment by nightdread** [comment]
@CADViewer I executed the permission.sh script according to the manual. 

[call-Api_Conversion_log (2).txt](https://github.com/CADViewer/NextCloud/files/13230957/call-Api_Conversion_log.2.txt)

**Comment by nightdread** [comment]
@CADViewer will you help me with my problem?

**Comment by CADViewer** [comment]
Hello @nightdread , we did a check when manually upgrading a box from Nextcloud 25 to Nextcloud 27, and after manually copying over the /apps/cadviewer/ tree, what was needed was to do the recursive setting of file ownership: 
 chown -R www-data:www-data cadviewer   , so see https://github.com/CADViewer/NextCloud/blob/main/README.md

**Comment by CADViewer** [comment]
Hello again @nightdread ,    so the log gives a conversion error, can you from a terminal run the command from the log:   /var/www/nextcloud/apps/cadviewer/converter//converters/ax2024/linux//ax2023_L64_23_12_120 -i="/var/www/nextcloud/apps/cadviewer/converter//converters/files/f278842664.dwg" -o="/var/www/nextcloud/apps/cadviewer/converter//converters/files/f278842664.svgz"  -f="svgz" -model -extents -fpath="/var/www/nextcloud/apps/cadviewer/converter//converters/ax2024/linux/fonts/"  -lpath="/var/www/nextcloud/apps/cadviewer/converter//converters/ax2024/linux/"  -xpath="/var/nextcloud/data/__groupfolders/4/"    , this will give indications if permissions on folders or executable is correct or not, you can then give 755 to all folders and the exe on the path and check again

**Comment by nightdread** [comment]
@CADViewer -bash: /var/www/nextcloud/apps/cadviewer/converter/converters/ax2024/linux/ax2023_L64_23_12_120: cannot execute binary file: Exec format error

**Comment by CADViewer** [comment]
@nightdread , open a terminal, navigate to the location of the executable: /var/www/nextcloud/apps/cadviewer/converter/converters/ax2024/linux   , from there run:  ./ax2023_L64_23_12_120 -?

**Comment by CADViewer** [comment]
@nightdread , we just uploaded CADViewer v9.17.2 , so you can remove CADViewer v8.88.5, and then update with 9.17.2 version, it's the same CAD converter ax2023_L64_23_12_120   ,  so repeat the process above.   Let me know the  outcome

**Comment by nightdread** [comment]
@CADViewer could it be because of the arm64 architecture?

**Comment by CADViewer** [comment]
@nightdread , you are absolutely right,  we support x86_64 architecture on the back-end.    A stable arm64 toolkit for CAD is not yet fully released.  We are a member of an industry organization that will provide support for this platform.

**Comment by CADViewer** [comment]
@nightdread , we can talk commercially about this directly, you can reach me on casper.harnung@tailormade.com.

**Comment by CADViewer** [comment]
arm64 support for back-end CAD converter not yet released.

**Comment by nightdread** [comment]
@CADViewer how soon can we expect arm64 support?)

**Comment by CADViewer** [comment]
@nightdread , we have customers outside of Nextcloud who are candidate for the arm64 port, I need however to understand your licensing needs in order to bundle you in with our general candidates on that platform, therefore please do get in touch on regular email.  I am casper.harnung@tailormade.com. Thanks!
