### ISSUE TITLE
Publish as PDF  is not working and hang  

### ISSUE THREAD

**Issue by kevinkuan1969** [CADViewer/NextCloud#70]
Nextcloud 27.1.2
CADViewer 8.88.5

Try to download dwg format file but cannot proceed. Kindly advise. Thanks.

**Comment by CADViewer** [comment]
Hello @kevinkuan1969 ,   we tested the PDF publish method in Nextcloud 27  /CADViewer 8.88.5, and can replicate your issue. We will get back to you shortly!

**Comment by CADViewer** [comment]
Hello @kevinkuan1969 , we have now posted CADViewer v9.17.2 which closes this issue.
