### ISSUE TITLE
Issue with docker-compose - blank page

### ISSUE THREAD

**Issue by overlaps1** [CADViewer/NextCloud#72]
Hi there,

Here is my setup:

Nginx ct as reverse proxy
Caddy ct for lets-encrypt certificate
Nextcloud ct

I have setup the permissions as mentionned on git and cadviewer doctor seems happy
I have modified the .htaccess
I have also modified in .htaccess  "/apps/..." path to "/custom_apps/..." as of my nextcloud setup.

Here is the nextcloud log error:
 
,"app":"PHP","method":"POST","url":"/apps/cadviewer/ajax/cadviewer.php","message":"Undefined array key \"parameters\" at /var/www/html/custom_apps/cadviewer/lib/Controller/CadviewerController.php#302"

should PHP POST url be also "/custom_apps/...."   ? 
in that case, where should I apply the right setup ? 

Thanks

**Comment by CADViewer** [comment]
Hello @overlaps1 , I think you possibly inside your rewrite rules needs to add a Rewrite condition to include the proper path for the custom_apps path, please check your current .htaccsss and update accordingly. Below is the rewrite cond /rewrite rule only.

```
<IfModule mod_rewrite_c>
	RewriteCond %{REQUEST_FILENAME} !/custom_apps/cadviewer/converter/php/*\.*
	RewriteRule . index.php [PT,E=PATH_INFO:$1]
<IfModule>
```

**Comment by overlaps1** [comment]
Thanks for your reply, I have done that already as mentionned in git readme file.
but no success:

```
`<IfModule mod_rewrite.c>
  Options -MultiViews
  RewriteRule ^core/js/oc.js$ index.php [PT,E=PATH_INFO:$1]
  RewriteRule ^core/preview.png$ index.php [PT,E=PATH_INFO:$1]
  RewriteCond %{REQUEST_FILENAME} !\.(css|js|svg|gif|png|html|ttf|woff2?|ico|jpg|jpeg|map|webm|mp4|mp3|ogg|wav|wasm|tflite)$
  RewriteCond %{REQUEST_FILENAME} !/core/ajax/update\.php
  RewriteCond %{REQUEST_FILENAME} !/core/img/(favicon\.ico|manifest\.json)$
  RewriteCond %{REQUEST_FILENAME} !/(cron|public|remote|status)\.php
  RewriteCond %{REQUEST_FILENAME} !/ocs/v(1|2)\.php
  RewriteCond %{REQUEST_FILENAME} !/robots\.txt
  RewriteCond %{REQUEST_FILENAME} !/(ocm-provider|ocs-provider|updater)/
  RewriteCond %{REQUEST_URI} !^/\.well-known/(acme-challenge|pki-validation)/.*
  RewriteCond %{REQUEST_FILENAME} !/richdocumentscode(_arm64)?/proxy.php$
  RewriteCond %{REQUEST_FILENAME} !/custom_apps/cadviewer/converter/php/*\.*
  RewriteRule . index.php [PT,E=PATH_INFO:$1]
  RewriteBase /
  <IfModule mod_env.c>
    SetEnv front_controller_active true
    <IfModule mod_dir.c>
      DirectorySlash off
    </IfModule>
  </IfModule>
</IfModule>
```

`

**Comment by overlaps1** [comment]
here is the full log line if it can help:

`{"reqId":"mB6bF0XwOB2pw5lzF9Iy","level":3,"time":"2023-11-29T09:17:00+00:00","remoteAddr":"_external_ip_","user":"_username_","app":"PHP","method":"POST","url":"/apps/cadviewer/ajax/cadviewer.php","message":"Undefined array key \"lineWeightFactor\" at /var/www/html/custom_apps/cadviewer/lib/Controller/CadviewerController.php#276","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36 Edg/119.0.0.0","version":"27.1.1.0","data":{"app":"PHP"}}
`

**Comment by overlaps1** [comment]
from that I have 2 things that hit me:
`"remoteAddr":"_external_ip_"` shouldn't it be the `internal_ip` ?
`"method":"POST","url":"/apps/cadviewer/ajax/cadviewer.php"` shouldn't it be `"method":"POST","url":"/custom_apps/cadviewer/ajax/cadviewer.php"` ?

**Comment by CADViewer** [comment]
OK, we will try to emulate the setup and see what we get, will keep you posted.

**Comment by overlaps1** [comment]
ok, thanks.
If it helps, here is my setup:
https://linuxiac.com/how-to-install-nextcloud-with-docker-compose/

**Comment by CADViewer** [comment]
thanks!  - will revert in a few days -

**Comment by Monoboy4ik** [comment]
@overlaps1 
try move /custom_apps/cadviewer to /apps/cadviewer and
RewriteCond %{REQUEST_FILENAME} !/apps/cadviewer/converter/php/*\.*

**Comment by CADViewer** [comment]
Hello @Monoboy4ik , with the latest version 9.47.1, we have added code to check the .httacess and update the rewrite conditions, and if there is insufficient permissions, we now provide an error message in the admin console with instructions.  Please check this version and let us know!    - If you have an issue, please re-open this ticket/create a new. - Thanks!

**Comment by overlaps1** [comment]
Hi support team !
I didn't have time to check your Last resolution. I Will check asap.
Thanks for your effort, it s really appreciated
Keep on the good job


Envoyé de mon mobile
Envoyé à partir de Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________
