### ISSUE TITLE
for demonstration purposes only tailor made software

### ISSUE THREAD

**Issue by zazo80** [CADViewer/NextCloud#73]
I installed the app (cadviewer) on nextcloud. When i open a .dwg i can view the file, but there is a text printed:

for demonstration purposes only tailor made software

How can i hide this message?

**Comment by sunjam** [comment]
Check out these other threads:
https://github.com/CADViewer/NextCloud/issues?q=is%3Aissue+demonstration

- https://github.com/CADViewer/NextCloud/issues/40
- https://github.com/CADViewer/NextCloud/issues/33

**Comment by CADViewer** [comment]
Hello @zazo80 ,  you need to license the software to remove the demonstration watermark,  please see our store: https://store.cadviewer.com/product/cadviewer-nextcloud-subscription/  ,  the base license is user based, where you in the admin interface can set which user has access at a given time.
