### ISSUE TITLE
CADViewer 9.20.5 + Nextcloud 28.0.1

### ISSUE THREAD

**Issue by dodoao** [CADViewer/NextCloud#74]
**Docker**
Nextcloud Log:
`Error
Call to undefined method OC\Server::getEventDispatcher()
App cadviewer threw an error during app.php load and will be disabled: Call to undefined method OC\Server::getEventDispatcher()`

I can't enable this application.

**Comment by CADViewer** [comment]
Hello @dodoao , yes probably removal of that method is a breaking change in Nextcloud 28, we are looking at this issue and will update you when we have a solution.

**Comment by Shxuai** [comment]
can't wait
![image](https://github.com/CADViewer/NextCloud/assets/26001241/513e554e-2280-4e2f-9c42-8f9dfe6943aa)

**Comment by CADViewer** [comment]
Hello @Shxuai, @dodoao , this issue is now solved, and CADViewer v9.38.6 has been uploaded!
