### ISSUE TITLE
NC 28.0.1, CADViewer 9.40.6 breaks viewing PDF and MD files

### ISSUE THREAD

**Issue by s-rosenfeld** [CADViewer/NextCloud#77]
If the application is enabled, the built-in PDF and MD file viewers stops working. If the application is disabled, functionality is restored.

**Comment by CADViewer** [comment]
Hi @s-rosenfeld , thanks, we will investigate and respond!

**Comment by hunasdf** [comment]
Same here. Browser's log:
Viewer.vue:639 Could not open file /Új munkafüzet.ods TypeError: t.replace is not a function
    at String.replaceAll (cadviewer_9.40.6.min.js:2:1493788)
    at index.js:53:4
    at O (index.js:109:9)
    at fileUtils.ts:66:26
    at Array.forEach (<anonymous>)
    at Z (fileUtils.ts:57:22)
    at oe (FileInfo.ts:44:12)
    at async o.openFile (Viewer.vue:630:1)

I hope it would be help :)

**Comment by lethargicpillow** [comment]
Encountering the same problem. Also affects other file types.

**Comment by CADViewer** [comment]
Hi @hunasdf , @s-rosenfeld , @lethargicpillow , we found a method overlap with NC28, in a code section where NC28 sets up paths for loading application files.  We have rewritten code on our end,  please test with new CADViewer v9.44.2 and provide feedback. Thanks!

**Comment by CADViewer** [comment]
OK, update verified by user.
