### ISSUE TITLE
CADViewer Conversion Server connection error

### ISSUE THREAD

**Issue by lethargicpillow** [CADViewer/NextCloud#79]
Got this app installed again after issue #74 was closed. But it still refuses to work.
Getting the following error:
CADViewer Conversion Server connection error, the endpoint is:
<DOMAIN>/apps/cadviewer/converter/php/call-Api_Conversion.php.
Please check your back-end server setup, and back-end/front-end url configuration.
(URL removed by me)
Not sure what else i can config. Cadviewer Doctor returns no errors. 

Found some errors in server logs. First one:
file_get_contents(/var/www/html/nextcloud/apps/cadviewer/appinfo/version.txt): Failed to open stream: No such file or directory at /var/www/html/nextcloud/apps/cadviewer/lib/Controller/CadviewerController.php#295
Second one shows some request to weird twin-slash path:
file_get_contents(/var/www/html/nextcloud/apps/cadviewer/converter//converter/converters/ax2024/linux/ax_font_map.txt): Failed to open stream: No such file or directory at /var/www/html/nextcloud/apps/cadviewer/lib/Controller/SettingsController.php#362 
Repeats at line 368.
Also found this one:
Could not find resource cadviewer/settings/l10n/en.js to load.

Any suggestions on how to fi this, I'm all ears.

Nextcloud 28.0.2. Cadviewer 9.40.6

**Comment by CADViewer** [comment]
Hi @lethargicpillow , can you please open the browser console, Ctrl+Shift+I, and list the trace when cadviewer attempts to communicate with the server to load files.  attach the trace as .txt (change your url with XXX if needed)  This will probably give us some additional information.  Also, send a screenshot, to show that CADViewer has correctly loaded icons, etc.  Thanks!

**Comment by Githopp192** [comment]
same error on nc 27.1.6, PHP 8.2, RHEL 8.9

![image](https://github.com/CADViewer/NextCloud/assets/32612067/f09f1dea-ea3a-46d0-8f53-e5e5c933cb30)

![image](https://github.com/CADViewer/NextCloud/assets/32612067/dd143137-1105-46d2-a351-5884fb60a50a)
![image](https://github.com/CADViewer/NextCloud/assets/32612067/0c464c70-b7d0-4559-8b3b-3bf2da1a8a89)

from the api conversion.log

/var/www/html/data/admin/filesXXX before file: 42 f166807363.svgzXXX file: 42 f166807363.svgzXXX param match: 0 f svgz XXX param match: 1 model XXX param match: 2 extents XXX timeStamp= 2023-11-23T09:31:52+0000 jarray['filecreatestamp']= 2023-11-20T09:10:41+00:00 timeStamp= 1700731912 jarray['filecreatestamp']= 1700471441 exec return1 0 output log: Directory Permissions: rwxr-xr-x Current User: www-data

Strange here is, that my apache user is NOT "www-data" !?

**Comment by Githopp192** [comment]
for any unknown reason: 

==>  RewriteCond %{REQUEST_FILENAME} !/apps/cadviewer/converter/php/*\.*

was not there anymore in ".htaccess" file. After adding this entry again (manually) - cadviewer works as expteced

**Comment by lethargicpillow** [comment]
> for any unknown reason:
> 
> ==> RewriteCond %{REQUEST_FILENAME} !/apps/cadviewer/converter/php/_._
> 
> was not there anymore in ".htaccess" file. After adding this entry again (manually) - cadviewer works as expteced

Yeah, that line somehow got absent from my .htaccess as well. I used this to replace the missing one:
RewriteCond %{REQUEST_FILENAME} !/apps/cadviewer/converter/php/*\.*
from nextcloud/apps/cadviewer/converter/nextcloud_AIO_sample.htaccess file and everything got working again.
Probably happened when Nextcloud updated itself and .htaccess as well. At least, sudo -u www-data php occ maintenance:update:htaccess replicates the problem by removing the needed line from file.

Thanks, Githopp!

**Comment by lethargicpillow** [comment]
Reopening issue after stubling into another weird problem. After applying changes from the previous post CadViewer tries to open all files now - docs, spreadsheets, pdfs, images, etc. Disabling CadViewer or removing the rewrite rule returns everything to the starting point. Any ideas on how to resolve this?

Log file attached.
[Uploading log-1707523278139.log…]()

**Comment by Githopp192** [comment]
those are the last lines of .htaccess file - you may need to place the cadviewer entry before " RewriteRule . index.php ..."

![image](https://github.com/CADViewer/NextCloud/assets/32612067/8764da0a-cb94-4a7f-8d3f-95f4c10652b2)

**Comment by lethargicpillow** [comment]
Entries look identical to mine. Something else is wrong.
![image](https://github.com/CADViewer/NextCloud/assets/98095269/d48e8431-cbce-451a-8211-0fd0c610b7e4)

UPD. Issues #77 and #78 are addrressing the same problem.

**Comment by lethargicpillow** [comment]
Sorry, could not answer earlier. Last update seems to fix all of the issues
