### ISSUE TITLE
Add Supported arch on nextcloud store description

### ISSUE THREAD

**Issue by Makotophoto** [CADViewer/NextCloud#83]
I think you should add a line in the nextcloud store description to say the supported architecture is only x86_64, and it does not support ARM.

I did get the problem.
Solved all the access right, and checked CADviewer Doctor (in the configuration).
The only hint I did get was when i flushed the cache, and it give me a warning telling that ax2023_L64_xx_yy_zz is not working.

Another workaround could be that CADviewer Doctor check the system architecture, but it may not be possible at his level.

**Comment by CADViewer** [comment]
Hi @Makotophoto , thanks good point this is added to info.xml, and will be up with next version.  Also internally, have added to investigate that the CADViewer Doctor makes this check also and provide an error message.   FYI: it's only now that the industry toolkit vendor is looking at arm support, so possibly it will filter through in the few next quarter.
