### ISSUE TITLE
Mimetype migration not working - Errors in log

### ISSUE THREAD

**Issue by sseide** [CADViewer/NextCloud#89]
On plugin activation CadViewer tries to install custom SVG images and others in NextCloud default image folder.
On my installation the "www-data" user PHP is run with does not have write access to this folder.

The Nextcloud protocol log shows errors similar to:
```
copy(/var/www/nextcloud/core/img/filetypes/dwf.svg): Failed to open stream: Permission denied at /var/www/nextcloud/apps/cadviewer/lib/Migration/RegisterMimeType.php#67 

file_put_contents(/var/www/nextcloud/core/js/mimetypelist.js): Failed to open stream: Permission denied at /var/www/nextcloud/core/Command/Maintenance/Mimetype/UpdateJS.php#52 

file_get_contents(/var/www/nextcloud/apps/cadviewer/appinfo/init.txt): Failed to open stream: No such file or directory at /var/www/nextcloud/apps/cadviewer/lib/Listeners/LoadScriptsListener.php#27 
```

Fixing file access rights was needed - allow group www-data to write to these locations:

```
chmod g+w /var/www/nextcloud/core/img/filetypes/
chmod g+w /var/www/nextcloud/core/js/mimetypelist.js
```
Afterwards i had to disable and re-eneable the plugin for a successful rerun of the migration.

Please update your README / FAQ and/or permission script accordingly.

**Comment by CADViewer** [comment]
Hello @sseide , can you please let us know, the version of Nextcloud  you are on, as well as install platform. Thanks!

**Comment by sseide** [comment]
Hello,

it was with Nextcloud 28.0.5 on Ubuntu 22.04 / amd64

It is the HanssonIT based Nextcloud VM - but original VM was from NC 22(?) with Ubuntu 20.04. It was constantly updated to current state:
 - NC 22 -> NC 25
 - Ubuntu 20.04 (with PHP 7.x) -> Ubuntu 22.04 (PHP 8.x)
 - NC 25 -> NC 28 -> NC 28.0.5

I do not know how much a newly downloaded VM with Nextcloud will differ...
And it seems it is not possible to download an older release (NC 28) from HanssonIT, only with current NC29.

Update to NC 29 is on hold as long as CadViewer is not marked compatible with it.

Best regards,
Stefan

**Comment by CADViewer** [comment]
Hello, @sseide , we have uploaded a new version compatible with NC29. Can you pleae update, check and let us know.  Many thanks!

**Comment by sseide** [comment]
Hello, yesterday found time to update and test.
First updated the plugin to latest version 9.71.1 with NC28 and updated Nextcloud to 29 afterwards.
Everything seems to work fine.

Thanks!

**Comment by CADViewer** [comment]
Hello @sseide , thanks! I will close this ticket now.    I am very interested to know more about how you (and others) are using CADViewer? Please drop a few words in the connection, eiher here or directly to my mail, you can find me on casper.harnung@tailormade.com. Thanks!
